<?php
// Pega a action atual, para
$action     = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$module     = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
?>

<!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if IE 7 ]>     <html lang="pt_BR" class="ie7">    <![endif]-->
<!--[if IE 8 ]>     <html lang="pt_BR" class="ie8">    <![endif]-->
<!--[if IE 9 ]>     <html lang="pt_BR" class="ie9">    <![endif]-->
<!--[if (gt IE 10)|!(IE)]><!--><html lang="pt_BR"><!--<![endif]-->
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="HandheldFriendly" content="true" />
        <?php
            $titulo = "Página inicial";

            echo $this->headTitle($titulo) . "\n";
            echo $this->HeadMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                    ->appendHttpEquiv('Description', $this->translate(""))
                    ->appendHttpEquiv('Keywords', $this->translate(""))
                    ->appendHttpEquiv('Content-Language', 'pt-BR')
                    ->appendHttpEquiv('GOOGLEBOT', 'index,follow')
                    ->appendHttpEquiv('revisit-after', '1 Day')
                    ->appendHttpEquiv('revisit-after', '1 Day')
                    ->appendHttpEquiv('Author', '')
                    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
                    ->appendName('viewport', 'width=device-width, initial-scale=1');
        ?>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">        

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

        <style>
            .mt-3 {margin-top: 3rem;}
            .mb-3 {margin-bottom: 3rem;}
        </style>
    </head>
    <body>

        <div class="container-fluid bg-primary">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="text-center">Sistema de teste ZF1</h3>
                </div>
            </div>
        </div>

        <div class="container mt-3">
            <div class="row">
                <div class="col-sm-12">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>        

        <div id="newSystemModal" class="modal fade" role="dialog" aria-hidden="true"> <div class="modal-dialog modal-lg"> <div class="modal-content"> <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button> <h4 class="modal-title">Título do Modal</h4> </div><div class="modal-body"> </div><div class="modal-footer"> <button type="button" class="btn btn-default" data-dismiss="modal">fechar</button> <button type="button" class="btn btn-primary">Enviar</button> </div></div></div></div>
        
        
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
        <script type="text/javascript" src="/js/modules/default/development.js"></script>

        <script>
            $("#dt_prazo_entrega").attr("type", "date");

            $(document).on("click", ".btnRmvItem", function() {
                let dataId = $(this).attr("data-id");
                let urlRemover = "/entrega/gestao/remover/co_entrega/"+dataId;

                if (confirm("deseja realmente remover esta entrega?")) {
                    $.post(urlRemover, {}, function(r) {
                        if (r.type === "success") {
                            $("#tblListaEntrega .ln-"+dataId).remove();
                        }
                    });
                }
            })
        </script>
    </body>
</html>
