
    <div class="col-sm-offset-1 col-sm-5 margin-top-40">
        <br /><br /><br />
        <h3>Permissão negada!</h3>
        <hr />
        <h5>A área que você esta tentando acessar é uma área restrita ao seu grupo de usuário.</h5><br />

        <div class="alert alert-warning">
            <strong>Esta mensagem pode estar aparecendo por um dos seguintes motivos:</strong><br />
            &nbsp;<strong>1-</strong> Sua sessão expirou enquanto você estava navegando pelo site.<br />
            &nbsp;<strong>2-</strong> Você esta tentando acessar uma área que você não possui permissão.<br />
            &nbsp;<strong>3-</strong> Você foi direcionado acidentalmente para este link.<br />
            &nbsp;<strong>4-</strong> A área que você procura no site não existe mais.<br />
        </div>
        <br />
    </div>


    <div class="col-sm-offset-1 col-sm-5 margin-top-40">
        <br /><br /><br />
        <h3 class="form-signin-heading">Diário Oficial - Admin</h3>
        <div class="alert alert-info">
            Caso seja seu primeiro acesso, sua senha é o seu CPF.
        </div>
        <?= $this->formulario ?>
    </div>



